In [5]:
# IMPORT NUMPY
import numpy as np

# MAKE SQUARES FROM 1^2 TO 100^2
A = np.arange(1, 101)**2
A = A.reshape(10, 10)  # PUT INTO 10X10 SHAPE

# PICK NUMBERS DIVISIBLE BY 3
div_by_3 = A[A % 3 == 0]

# SAVE THEM TO FILE
np.save("div_by_3.npy", div_by_3)

# PRINT
print("10X10 ARRAY OF SQUARES:\n", A)
print("\nNUMBERS DIVISIBLE BY 3:\n", div_by_3)


10X10 ARRAY OF SQUARES:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

NUMBERS DIVISIBLE BY 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [8]:
# IMPORT NUMPY
import numpy as np

# MAKE A 5X5 ARRAY
X = np.random.rand(5, 5)

# FORMULA: (X - MEAN) / STD
X_normalized = (X - X.mean()) / X.std()

# SAVE IT TO FILE
np.save("X_normalized.npy", X_normalized)

# PRINT
print("ORIGINAL ARRAY:\n", X)
print("\nNORMALIZED ARRAY:\n", X_normalized)


ORIGINAL ARRAY:
 [[0.32030286 0.96649417 0.66290591 0.11036511 0.97851298]
 [0.45641676 0.26797211 0.91872387 0.11726652 0.71789736]
 [0.93886474 0.52139303 0.11001642 0.52104288 0.93058141]
 [0.59932374 0.62086423 0.52185906 0.31796758 0.0937933 ]
 [0.17939228 0.26149734 0.15362756 0.84347606 0.94574078]]

NORMALIZED ARRAY:
 [[-0.65174498  1.42546284  0.44956625 -1.32659826  1.4640978 ]
 [-0.2142014  -0.81996428  1.27190332 -1.30441343  0.62633847]
 [ 1.33664694 -0.00533257 -1.32771915 -0.00645814  1.31001985]
 [ 0.24517881  0.31442159 -0.00383452 -0.65925182 -1.37986902]
 [-1.10470769 -0.84077768 -1.18752941  1.03001623  1.35875026]]
